[package]
name = "checksums3"
version = "0.1.0"
edition = "2021"

[dependencies]

lambda_runtime = "0.7"
serde = "1.0.136"
tokio = { version = "1", features = ["macros"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt"] }
rayon = "1.5.1"
md5 = "0.7.0"
