[package]
name = "onnx_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
onnxruntime = "0.0.14"
clap = {version="4.0.32", features=["derive"]}
tracing = "0.1"
tracing-subscriber = "0.3.16"